Repository icarofilho/bookshelf_v1_soul-code, pull requests merged in 2022-01, with the labels that each got.

#10 Recaptcha
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/app-login/app-login.component.html
  src/app/app-login/app-login.component.ts
  src/app/app.module.ts
Labels: bug

#12 Login google
  src/app/app-login/app-login.component.html
  src/app/app-login/app-login.component.scss
  src/app/app-login/app-login.component.ts
  src/app/servicosInterface/autenticacao-firebase.service.ts
Labels: implementacao

#16 Boas vindas user
  src/app/feed/feed.component.html
  src/app/feed/feed.component.scss
Labels: experiência

#19 Feature clearfields
  src/app/app-login/app-login.component.ts
  src/app/cdd/classes/classes.component.html
Labels: documentação

#21 Endpoint Especial Mês [5 pts] #81
  src/app/modelosInterface/reportagens.ts
  src/assets/imagens/imagem1.png
  src/assets/imagens/imagem2.png
  src/assets/imagens/imagem3.png
  src/assets/imagens/imagem4.png
  src/assets/reportagens.json
Labels: implementacao, experiência

#23 Cartao#49 Logo Cartões Dashboard
  src/app/feed/feed.component.scss
Labels: bug

#24 limpeza de campos pré login
  src/app/app-login/app-login.component.ts
Labels: bug

#27 Cartao#57 Melhorias de divisores Feed
  src/app/feed/feed.component.html
  src/app/feed/feed.component.scss
Labels: experiência

#29 Serviço Especial Mês [10 pts] #80
  src/app/modelosInterface/especialMes.ts
  src/app/servicosInterface/especial-mes.service.spec.ts
  src/app/servicosInterface/especial-mes.service.ts
  src/assets/especialMes.json
Labels: implementacao, experiência

#30 component recuperar senha
  src/app/app-login/app-login.component.html
  src/app/app-login/app-login.component.scss
  src/app/app-login/app-login.component.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/recuperar-senha/recuperar-senha.component.html
  src/app/recuperar-senha/recuperar-senha.component.scss
  src/app/recuperar-senha/recuperar-senha.component.spec.ts
  src/app/recuperar-senha/recuperar-senha.component.ts
Labels: bug, implementacao, experiência

#31 Melhorias para Tela de Cadastro [25 pts] #21
  .vscode/settings.json
  src/app/app-cadastro/app-cadastro.component.html
  src/app/app-cadastro/app-cadastro.component.scss
  src/app/app-cadastro/app-cadastro.component.ts
  src/app/app-compartilhado/app-compartilhado.module.ts
  src/app/app.module.ts
Labels: experiência

#32 Pagina Especial Mês [15 pts] #79
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/especial-mes/especial-mes.component.html
  src/app/especial-mes/especial-mes.component.scss
  src/app/especial-mes/especial-mes.component.spec.ts
  src/app/especial-mes/especial-mes.component.ts
  src/assets/especialMes.json
  src/assets/imagens/imagem3.png
  src/assets/menuNavegador.json
Labels: implementacao

#33 Recuperar senha service
  src/app/recuperar-senha/recuperar-senha.component.html
  src/app/recuperar-senha/recuperar-senha.component.ts
  src/app/servicosInterface/autenticacao-firebase.service.ts
Labels: bug, implementacao, experiência

#52 Melhorias de Botão Usuário [15 pts] #19
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.scss
Labels: experiência

#53 Melhor dialog login#20
  src/app/app-login/app-login.component.scss
Labels: implementacao, experiência

#55 Falha de Logout [15 pts] #4
  src/app/navegacao/navegacao.component.ts
Labels: bug, implementacao

#56 Cartao53 -Carregamento para página de Feed
  src/app/cdd/classes/classes.component.html
  src/app/feed/feed.component.html
  src/app/feed/feed.component.scss
  src/app/feed/feed.component.ts
  src/app/servicosInterface/dashboard.service.ts
  src/assets/dashboard.json
Labels: experiência

#69 pagina isbn com informacoes ao usuario
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/isbn/isbn.component.html
  src/app/isbn/isbn.component.scss
  src/app/isbn/isbn.component.spec.ts
  src/app/isbn/isbn.component.ts
  src/assets/imagens/classes-dewey.jpg
  src/assets/imagens/estante1.jpg
  src/assets/imagens/isbn.png
  src/assets/menuNavegador.json
Labels: implementacao

#72 E-mail no alto do menu [10 pts] #25
  src/app/app-compartilhado/app-compartilhado.module.ts
  src/app/app-compartilhado/app-pipes/user-name-from-email.pipe.spec.ts
  src/app/app-compartilhado/app-pipes/user-name-from-email.pipe.ts
  src/app/app.module.ts
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.scss
Labels: implementacao

#73 Rotas Desconhecidas [15 pts] #22
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/rotas-desconhecidas/rotas-desconhecidas.component.html
  src/app/rotas-desconhecidas/rotas-desconhecidas.component.scss
  src/app/rotas-desconhecidas/rotas-desconhecidas.component.spec.ts
  src/app/rotas-desconhecidas/rotas-desconhecidas.component.ts
Labels: implementacao, experiência

#74 Inclusão endpoint e interface biblioteconomia
  src/app/modelosInterface/biblioteconomia.ts
  src/assets/biblioteconomia.json
  src/assets/imagens/biblio1.jpg
  src/assets/imagens/biblio2.jpg
  src/assets/imagens/biblio3.png
  src/assets/imagens/biblio4.jpg
Labels: implementacao, experiência

#76 Melhoria no Menu [10 pts] #58
  src/app/app-compartilhado/app-material/app-material.module.ts
  src/app/app.module.ts
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.scss
Labels: experiência

#77 Criado serviço biblioteconomia #74
  src/app/servicosInterface/biblioteconomia.service.spec.ts
  src/app/servicosInterface/biblioteconomia.service.ts
Labels: implementacao, experiência

#109 form reativo cdd
  src/app/app-compartilhado/app-material/app-material.module.ts
  src/app/cdd/cdd.module.ts
  src/app/cdd/classes/classes.component.html
  src/app/cdd/classes/classes.component.scss
  src/app/cdd/classes/classes.component.ts
  src/app/cdd/service/generos.service.ts
Labels: implementacao

#110 component de susgestoes
  src/app/app-compartilhado/app-material/app-material.module.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/sugestoes/sugestoes.component.html
  src/app/sugestoes/sugestoes.component.scss
  src/app/sugestoes/sugestoes.component.spec.ts
  src/app/sugestoes/sugestoes.component.ts
  src/assets/menuNavegador.json
Labels: implementacao, experiência

#111 Cores da Toolbar [10 pts] #48
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.scss
  src/app/navegacao/navegacao.component.ts
Labels: experiência

#112 Cartao8- Página de Livros para Vestibular
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/modelosInterface/vestibular.ts
  src/app/servicosInterface/vestibular.service.spec.ts
  src/app/servicosInterface/vestibular.service.ts
  src/app/vestibular/vestibular.component.html
  src/app/vestibular/vestibular.component.scss
  src/app/vestibular/vestibular.component.spec.ts
  src/app/vestibular/vestibular.component.ts
  src/assets/imagens/cartao_ita.jpg
  src/assets/imagens/cartao_ita2.jpg
  src/assets/imagens/cartao_uerj.jpg
  src/assets/imagens/cartao_ufpr.jpg
  src/assets/imagens/cartao_unicamp.jpg
  src/assets/imagens/logo_uerj
  src/assets/menuNavegador.json
  src/assets/vestibular.json
Labels: implementacao

#113 ajuste tabela cdd
  src/app/app-cadastro/app-cadastro.component.html
  src/app/cdd/classes/classes.component.html
  src/app/cdd/classes/classes.component.scss
Labels: experiência

#114 Rotina para limpar campos de cadastro. [10 pts] #51
  src/app/app-cadastro/app-cadastro.component.ts
Labels: experiência

#115 Imagem View Celular [15 pts] #3
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/feed/feed.component.html
  src/app/feed/feed.component.scss
  src/app/feed/feed.component.ts
  src/app/servicosInterface/main-card.service.spec.ts
  src/app/servicosInterface/main-card.service.ts
  src/assets/dashboard.json
  src/assets/mainCard.json
Labels: bug, sustentação

#116 Imagem View Celular [15 pts] #3
  src/app/app-cadastro/app-cadastro.component.html
  src/app/app-cadastro/app-cadastro.component.scss
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.scss
  src/app/navegacao/navegacao.component.ts
Labels: experiência

#117 Cartao23- Melhorias nos cartoes do Feed
  src/app/feed/feed.component.html
  src/app/feed/feed.component.scss
  src/app/feed/feed.component.ts
Labels: experiência

#118 Tratamento de Erros [25 pts] #16
  src/app/app-cadastro/app-cadastro.component.ts
  src/app/app-login/app-login.component.ts
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.scss
Labels: bug, implementacao

#119 Cartao-Rotina de busca no Feed
  src/app/feed/feed.component.html
  src/app/feed/feed.component.scss
  src/app/feed/feed.component.ts
  src/app/servicosInterface/dashboard.service.ts
Labels: implementacao

#120 pagina mais vendidos, endpoints br e mundo, servico de listagem
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/mais-vendidos/mais-vendidos.component.html
  src/app/mais-vendidos/mais-vendidos.component.scss
  src/app/mais-vendidos/mais-vendidos.component.spec.ts
  src/app/mais-vendidos/mais-vendidos.component.ts
  src/app/mais-vendidos/modelos/maisVendidos.ts
  src/app/servicosInterface/maisvendidos.service.spec.ts
  src/app/servicosInterface/maisvendidos.service.ts
  src/assets/maisVendidosMundo.json
  src/assets/maisvendidosbrasil.json
  src/assets/menuNavegador.json
Labels: implementacao

#121 Modulo Biblioteconomia [15 pts] #73
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/biblioteconomia/biblioteconomia.component.html
  src/app/biblioteconomia/biblioteconomia.component.scss
  src/app/biblioteconomia/biblioteconomia.component.spec.ts
  src/app/biblioteconomia/biblioteconomia.component.ts
  src/app/feed/feed.component.scss
  src/app/feed/feed.component.ts
  src/app/modelosInterface/biblioteconomia.ts
  src/app/servicosInterface/biblioteconomia.service.ts
  src/assets/biblioteconomia.json
  src/assets/menuNavegador.json
Labels: implementacao, experiência

#122 Endpoint de Sagas [5 pts] #65
  src/assets/imagens/saga1.jpg
  src/assets/imagens/saga2.jpeg
  src/assets/imagens/saga3.jpg
  src/assets/imagens/saga4.jpg
  src/assets/sagas.json
Labels: implementacao, experiência

#124 Criação serviço sagas
  src/app/modelosInterface/sagas.ts
  src/app/servicosInterface/sagas.service.spec.ts
  src/app/servicosInterface/sagas.service.ts
Labels: implementacao, experiência

#126 Implementação de Tela do Usuário [25 pts] #26
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/feed/feed.component.scss
  src/app/rotas-desconhecidas/rotas-desconhecidas.component.html
  src/app/rotas-desconhecidas/rotas-desconhecidas.component.scss
  src/app/tela-usuario/tela-usuario.component.html
  src/app/tela-usuario/tela-usuario.component.scss
  src/app/tela-usuario/tela-usuario.component.spec.ts
  src/app/tela-usuario/tela-usuario.component.ts
  src/assets/menuNavegador.json
Labels: implementacao

#127 parcial de implementação upload-img-profile + correção de menu
  src/app/app-cadastro/app-cadastro.component.html
  src/app/app-cadastro/app-cadastro.component.ts
  src/app/navegacao/navegacao.component.scss
  src/app/servicosInterface/autenticacao-firebase.service.ts
Labels: bug

#128 Solucao view dashboard
  src/app/app-cadastro/app-cadastro.component.ts
  src/app/cdd/classes/classes.component.html
  src/app/cdd/classes/classes.component.ts
  src/app/feed/feed.component.html
  src/app/feed/feed.component.ts
  src/app/modelosInterface/dashboard.ts
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.scss
  src/app/servicosInterface/dashboard.service.ts
  src/app/servicosInterface/main-card.service.ts
  src/assets/dashboard.json
  src/assets/imagens/anos00.jpg
  src/assets/menuNavegador.json
Labels: experiência

#129 endpoint sugestoes e ajuste css mais-vendidos
  src/app/mais-vendidos/mais-vendidos.component.scss
  src/assets/sugestoes.json
Labels: implementacao, experiência

#130 Endpoint de Teatro [5 pts] #42
  src/assets/teatro.json
Labels: implementacao, experiência

#131 Serviço de Teatro [10 pts] #41
  src/app/modelosInterface/teatro.ts
  src/app/servicosInterface/teatro.service.spec.ts
  src/app/servicosInterface/teatro.service.ts
Labels: implementacao

#133 Cartao13-Wiki BookShelf-[Painel de Ajuda com uso da wiki]
  src/app/ajuda/ajuda.component.html
  src/app/ajuda/ajuda.component.scss
  src/app/ajuda/ajuda.component.spec.ts
  src/app/ajuda/ajuda.component.ts
  src/app/app-compartilhado/app-compartilhado.module.ts
  src/app/app-compartilhado/app-pipes/ajuda-icon.pipe.spec.ts
  src/app/app-compartilhado/app-pipes/ajuda-icon.pipe.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/modelosInterface/ajuda.ts
  src/app/servicosInterface/ajuda.service.spec.ts
  src/app/servicosInterface/ajuda.service.ts
  src/assets/ajuda.json
  src/assets/menuNavegador.json
Labels: implementacao, documentação

#134 Criação Endpoint Artes
  src/app/biblioteconomia/biblioteconomia.component.scss
  src/assets/artes.json
Labels: implementacao

#136 Pagina de Teatro [15 pts] #40
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/teatro/teatro.component.html
  src/app/teatro/teatro.component.scss
  src/app/teatro/teatro.component.spec.ts
  src/app/teatro/teatro.component.ts
  src/assets/menuNavegador.json
Labels: implementacao

#138 Criação Serviço e Interface Artes
  src/app/modelosInterface/artes.ts
  src/app/servicosInterface/artes.service.spec.ts
  src/app/servicosInterface/artes.service.ts
Labels: implementacao

#139 Sugestoes service
  src/app/servicosInterface/sugestoes.service.spec.ts
  src/app/servicosInterface/sugestoes.service.ts
  src/app/sugestoes/modelos/sugestoes.ts
  src/app/sugestoes/sugestoes.component.html
  src/app/sugestoes/sugestoes.component.scss
  src/app/sugestoes/sugestoes.component.ts
  src/assets/sugestoes.json
Labels: implementacao, experiência

#140 Criação modulo artes
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/artes/artes.component.html
  src/app/artes/artes.component.scss
  src/app/artes/artes.component.spec.ts
  src/app/artes/artes.component.ts
  src/app/modelosInterface/artes.ts
  src/app/servicosInterface/artes.service.ts
  src/assets/artes.json
  src/assets/menuNavegador.json
Labels: implementacao

#141 Endpoint Direito # 39
  src/app/modelosInterface/direito.ts
  src/app/navegacao/navegacao.component.scss
  src/assets/direito.json
Labels: implementacao, experiência

#142 Criação Endpoint Tecnologia
  src/assets/tecnologia.json
Labels: implementacao

#143 Serviço de Direito [10 pts] #38
  src/app/servicosInterface/direito.service.spec.ts
  src/app/servicosInterface/direito.service.ts
Labels: implementacao

#145 Criação Serviço e Inteface Tecnologia #35
  src/app/modelosInterface/tecnologia.ts
  src/app/servicosInterface/tecnologia.service.spec.ts
  src/app/servicosInterface/tecnologia.service.ts
Labels: implementacao

#146 Criação componente Tecnologia #34
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/tecnologia/tecnologia.component.html
  src/app/tecnologia/tecnologia.component.scss
  src/app/tecnologia/tecnologia.component.spec.ts
  src/app/tecnologia/tecnologia.component.ts
  src/assets/menuNavegador.json
Labels: implementacao

#147 Pagina direito #37
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/direito/direito.component.html
  src/app/direito/direito.component.scss
  src/app/direito/direito.component.spec.ts
  src/app/direito/direito.component.ts
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.scss
  src/assets/direito.json
  src/assets/menuNavegador.json
Labels: implementacao

#148 Busca de Sagas [15 pts] #70
  src/app/sagas/sagas.component.html
  src/app/sagas/sagas.component.scss
  src/app/sagas/sagas.component.ts
  src/app/servicosInterface/sagas.service.ts
Labels: bug, implementacao

#150 Criação serviço e interface empreendedorismo
  src/app/modelosInterface/empreendedorismo.ts
  src/app/servicosInterface/empreendedorismo.service.spec.ts
  src/app/servicosInterface/empreendedorismo.service.ts
Labels: implementacao

#151 Criação componente Empreendedorismo #28
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/empreendedorismo/empreendedorismo.component.html
  src/app/empreendedorismo/empreendedorismo.component.scss
  src/app/empreendedorismo/empreendedorismo.component.spec.ts
  src/app/empreendedorismo/empreendedorismo.component.ts
  src/app/servicosInterface/empreendedorismo.service.ts
  src/assets/empreendedorismo.json
  src/assets/menuNavegador.json
Labels: implementacao

#152 Endpoint criticas
  src/app/app-routing.module.ts
  src/app/criticas/critica/critica.component.html
  src/app/criticas/critica/critica.component.scss
  src/app/criticas/critica/critica.component.spec.ts
  src/app/criticas/critica/critica.component.ts
  src/app/criticas/criticas-routing.module.ts
  src/app/criticas/criticas.module.ts
  src/app/criticas/modelos/criticas.ts
  src/app/criticas/todas-criticas/todas-criticas.component.html
  src/app/criticas/todas-criticas/todas-criticas.component.scss
  src/app/criticas/todas-criticas/todas-criticas.component.spec.ts
  src/app/criticas/todas-criticas/todas-criticas.component.ts
  src/app/servicosInterface/criticas.service.spec.ts
  src/app/servicosInterface/criticas.service.ts
  src/app/sugestoes/sugestoes.component.scss
  src/assets/criticas.json
  src/assets/menuNavegador.json
Labels: implementacao, experiência

#153 adicionado tooltips e alterado layout da pagina Direito
  src/app/app.module.ts
  src/app/cdd/cdd.module.ts
  src/app/cdd/classes/classes.component.html
  src/app/direito/direito.component.html
  src/app/direito/direito.component.scss
  src/app/direito/direito.component.ts
  src/app/empreendedorismo/empreendedorismo.component.html
  src/app/navegacao/navegacao.component.html
Labels: implementacao

#154 Endpoint de Psicologia [5 pts] #45
  src/app/modelosInterface/psicologia.ts
  src/assets/psicologia.json
Labels: implementacao, experiência

#155 Serviço de Psicologia [15 pts] #44
  src/app/servicosInterface/psicologia.service.spec.ts
  src/app/servicosInterface/psicologia.service.ts
  src/app/servicosInterface/teatro.service.ts
  src/app/tela-usuario/tela-usuario.component.scss
Labels: implementacao

#156 Cartao11-WiKi: BookShelf v1 Caso de Uso Login
  src/app/ajuda/ajuda.component.html
  src/app/ajuda/ajuda.component.scss
  src/app/ajuda/ajuda.component.ts
  src/app/app-compartilhado/app-pipes/ajuda-icon.pipe.ts
  src/app/modelosInterface/ajuda.ts
  src/assets/ajuda.json
Labels: implementacao, documentação
