Repository icarofilho/bookshelf_v1_soul-code, pull requests merged in 2022-02, with the labels that each got.

#158 Dialog criticas
  src/app/criticas/critica-dialog/critica-dialog.component.html
  src/app/criticas/critica-dialog/critica-dialog.component.scss
  src/app/criticas/critica-dialog/critica-dialog.component.spec.ts
  src/app/criticas/critica-dialog/critica-dialog.component.ts
  src/app/criticas/critica/critica.component.ts
  src/app/criticas/criticas.module.ts
  src/app/criticas/todas-criticas/todas-criticas.component.html
  src/app/criticas/todas-criticas/todas-criticas.component.scss
  src/app/criticas/todas-criticas/todas-criticas.component.ts
Labels: implementacao, experiência

#159 correcao menuNavegador json/visual e component de pesquisa criticas
  src/app/criticas/todas-criticas/todas-criticas.component.html
  src/app/criticas/todas-criticas/todas-criticas.component.scss
  src/app/direito/direito.component.html
  src/app/modelosInterface/menuNavegador.ts
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.ts
  src/app/vestibular/vestibular.component.html
  src/assets/menuNavegador.json
Labels: implementacao, experiência

#161 Ajustes no Menu de Ajuda [EXTRA]
  src/app/ajuda/ajuda.component.html
  src/app/ajuda/ajuda.component.scss
  src/app/ajuda/ajuda.component.ts
  src/app/modelosInterface/ajuda.ts
  src/app/servicosInterface/ajuda.service.ts
  src/app/vestibular/vestibular.component.html
  src/app/vestibular/vestibular.component.scss
  src/assets/ajuda.json
Labels: bug, implementacao

#163 Correção Tabela Direito
  src/app/direito/direito.component.html
  src/app/direito/direito.component.scss
  src/app/direito/direito.component.ts
Labels: bug

#166 Wiki errors
  src/app/ajuda/ajuda.component.html
  src/app/ajuda/ajuda.component.scss
  src/app/app-cadastro/app-cadastro.component.ts
  src/app/app-login/app-login.component.ts
  src/app/feed/feed.component.scss
  src/app/servicosInterface/autenticacao-firebase.service.ts
  src/assets/menuNavegador.json
Labels: documentação

#170 Melhoria pagina Sugestões
  src/app/sugestoes/sugestoes.component.html
  src/app/sugestoes/sugestoes.component.scss
  src/assets/sugestoes.json
Labels: experiência

#171 Ajustes Finais [EXTRA]
  src/app/ajuda/ajuda.component.html
  src/app/ajuda/ajuda.component.scss
  src/app/ajuda/ajuda.component.ts
  src/app/app-cadastro/app-cadastro.component.html
  src/app/app-cadastro/app-cadastro.component.ts
  src/app/modelosInterface/ajuda.ts
  src/app/modelosInterface/biblioteconomia.ts
  src/app/modelosInterface/dashboard.ts
  src/app/modelosInterface/especialMes.ts
  src/app/modelosInterface/sagas.ts
  src/app/modelosInterface/tecnologia.ts
  src/app/modelosInterface/vestibular.ts
  src/app/servicosInterface/ajuda.service.ts
  src/assets/ajuda.json
  src/assets/erros.json
Labels: bug, implementacao

#172 Pull final version
  README.md
  src/app/app-cadastro/app-cadastro.component.html
  src/app/app-cadastro/app-cadastro.component.ts
  src/app/app-login/app-login.component.ts
  src/app/navegacao/navegacao.component.html
  src/app/servicosInterface/autenticacao-firebase.service.ts
  src/app/tela-usuario/tela-usuario.component.html
  src/app/tela-usuario/tela-usuario.component.scss
  src/app/tela-usuario/tela-usuario.component.ts
  src/assets/erros.json
  src/assets/imagens/profile.png
Labels: bug
